spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
      filter:
        stat:
          merge-sql: true
          enabled: true
        wall:
          enabled: true
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        login-password: admin
        reset-enable: true
      web-stat-filter:
        enabled: true
        url-pattern:
      aop-patterns: com.qfggk.blog.*
  thymeleaf:
    enabled: true

logging:
  level:
    root: info
    com.qfggk: debug
  file:
    path: log/blog-dev.log
server:
  port: 8081


